apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: sample- # This is the single line to change for the "name"

# Namespace for this instance, if you use namespaces
namespace: minecraft-sample

resources:
  - ../../base
  - namespace.yaml

# Replaced 'commonLabels:' with 'labels:' transformer
labels:
- pairs:
    instance: sample # This label is primarily for organization/selection now
  includeSelectors: true # Ensures selectors are updated if they use this label
  includeTemplates: true # Ensures pod templates get this label if they match

patches:
  # Patch Minecraft Server StatefulSet (image, env vars, claimNames)
  - target:
      kind: StatefulSet
      name: minecraft-server # Name from base
    path: minecraft-server-config.yaml

  # Patch Bluemap Deployment (Minecraft world PVC claimName, Bluemap data PVC claimName, ConfigMap names)
  - target:
      kind: Deployment
      name: bluemap-web # Name from base
    path: bluemap-deployment-patch.yaml # Renamed patch file for clarity

  # (Optional) Patch Bluemap ConfigMaps if you need to tweak specific settings
  # - target:
  #     kind: ConfigMap
  #     name: bluemap-core-config # Name from base
  #   patch: |-
  #     apiVersion: v1
  #     kind: ConfigMap
  #     metadata:
  #       name: bluemap-core-config
  #     data:
  #       core.conf: |
  #         accept-download: true # Overridden value
  #         render-thread-count: 3 # Overridden value
  # - target:
  #     kind: ConfigMap
  #     name: bluemap-map-config
  #   patch: |-
  #     apiVersion: v1
  #     kind: ConfigMap
  #     metadata:
  #       name: bluemap-map-config
  #     data:
  #       overworld.conf: |
  #         world: "world"
  #         name: "Overworld" # Custom name
  #         # Add other specific map settings

# (Optional) Uncomment to include patches for existing world or Spigot JAR
# patchesStrategicMerge:
#   - provide-existing-world.yaml
#   - provide-spigot-jar.yaml
