# Include this in overlay's kustomization.yaml's 'patchesStrategicMerge' or 'patches' list
# if you want to use a custom JAR from a hostPath.
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft-server # Will be prefixed
spec:
  template:
    spec:
      containers:
      - name: minecraft-server-container
        env:
        - name: TYPE
          value: CUSTOM
        - name: CUSTOM_SERVER
          value: "/jars/custom-mc.jar"
        volumeMounts:
        - name: custom-jar
          mountPath: /jars/custom-mc.jar # Must match $CUSTOM_SERVER
          readOnly: true
      volumes:
      - name: custom-jar
        hostPath:
          path: /home/minecraft/servers/overlays/sample/my-custom-jar.jar # Actual path on your k3s node
          type: File
