apiVersion: v1
kind: ConfigMap
metadata:
  name: bluemap-core-config # Will be prefixed
data:
  core.conf: |
    accept-download: true
    data: "bluemap" 
    render-thread-count: 2 # Default, can be patched